// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.12.4
// source: bufs/v1/invoice.proto

package invoicer

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	InvoicerService_Create_FullMethodName = "/bufs.v1.InvoicerService/Create"
)

// InvoicerServiceClient is the client API for InvoicerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type InvoicerServiceClient interface {
	Create(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*CreateResponse, error)
}

type invoicerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewInvoicerServiceClient(cc grpc.ClientConnInterface) InvoicerServiceClient {
	return &invoicerServiceClient{cc}
}

func (c *invoicerServiceClient) Create(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*CreateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateResponse)
	err := c.cc.Invoke(ctx, InvoicerService_Create_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// InvoicerServiceServer is the server API for InvoicerService service.
// All implementations must embed UnimplementedInvoicerServiceServer
// for forward compatibility.
type InvoicerServiceServer interface {
	Create(context.Context, *CreateRequest) (*CreateResponse, error)
	mustEmbedUnimplementedInvoicerServiceServer()
}

// UnimplementedInvoicerServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedInvoicerServiceServer struct{}

func (UnimplementedInvoicerServiceServer) Create(context.Context, *CreateRequest) (*CreateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedInvoicerServiceServer) mustEmbedUnimplementedInvoicerServiceServer() {}
func (UnimplementedInvoicerServiceServer) testEmbeddedByValue()                         {}

// UnsafeInvoicerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to InvoicerServiceServer will
// result in compilation errors.
type UnsafeInvoicerServiceServer interface {
	mustEmbedUnimplementedInvoicerServiceServer()
}

func RegisterInvoicerServiceServer(s grpc.ServiceRegistrar, srv InvoicerServiceServer) {
	// If the following call pancis, it indicates UnimplementedInvoicerServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&InvoicerService_ServiceDesc, srv)
}

func _InvoicerService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InvoicerServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InvoicerService_Create_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InvoicerServiceServer).Create(ctx, req.(*CreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// InvoicerService_ServiceDesc is the grpc.ServiceDesc for InvoicerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var InvoicerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "bufs.v1.InvoicerService",
	HandlerType: (*InvoicerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _InvoicerService_Create_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "bufs/v1/invoice.proto",
}
